name: 'Publish'
on:
    push:
        branches:
            - master

jobs:
    publish-tauri:
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
            - name: install app dependencies and build it
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              run: |
                  npm ci
                  npm run build
            - uses: tauri-apps/tauri-action@v0
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: replicarma-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: ReplicArma v__VERSION__
                  releaseBody: ''
                  releaseDraft: true
                  prerelease: false