name: 'publish'

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest]
        include:
          - platform: windows-latest
            release_file_executable: ./src-tauri/target/release/ReplicArma.exe
            release_file_installer: ./src-tauri/target/release/bundle/msi/*.msi
            release_file_updater: ./src-tauri/target/release/bundle/msi/*.msi.zip
          - platform: ubuntu-latest
            release_file_executable: ./src-tauri/target/release/replic-arma
            release_file_installer: ./src-tauri/target/release/bundle/appimage/*.AppImage
            release_file_updater: ./src-tauri/target/release/bundle/appimage/*.tar.gz

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Build Tauri
        run: |
          npm ci
          npm run build

      - name: Upload asset (executable)
        uses: shogo82148/actions-upload-release-asset@v1
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.release_file_executable }}

      - name: Upload asset (installer)
        uses: shogo82148/actions-upload-release-asset@v1
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.release_file_installer }}

      - name: Upload asset (updater)
        uses: shogo82148/actions-upload-release-asset@v1
        with: 
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.release_file_updater }}
